### ISSUE TITLE
Wyświetlanie danych o klientach z poziomu Panela Administratora

### ISSUE THREAD

**Issue by xEdziu** [xEdziu/Klama#17]
## TODO

- [x] dane osobowe klienta,
- [x] historia karnetów klienta,
- [x] historia zakupów klienta,
- [x] historia rezerwacja sprzętu z wypożyczalni,
- [x] historia wypożyczenia sprzętu z wypożyczalni
