### ISSUE TITLE
Rejestracja i logowanie się użytkowników

### ISSUE THREAD

**Issue by xEdziu** [xEdziu/Klama#4]
# TODO

Do zrobienia są:

- [x] sysytem rejestracji użytkowników
- [x] system potwierdzania email użytkowników
- [x] endpointy
- [x] encja użytkownika z rolami `admin`, `user`
- [x] wytestowanie api w jetcliencie
